### ISSUE TITLE
Code for plotting causal graphs

### ISSUE THREAD

**Issue by vipulbjj** [iancovert/Neural-GC#1]
Can you please provide the code you used to plot Figure 5 in the paper?

**Comment by manmeet3591** [comment]
I am also looking forward to the codes used to plot the figure 9 in the paper

**Comment by iancovert** [comment]
Hi there, unfortunately I don't have this code to share. We had technology issues at one point and lost some of our earlier code, including the plotting code for the motion capture figure. Sorry about that, we know from experience that writing this code from scratch is quite tedious...
